networks:
  database_net:
    driver: bridge

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=tsuchen
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=piscineds
    ports:
      - "5432:5432"
    volumes:
      - /tmp/postgres-data:/var/lib/postgresql/data
    networks:
      - database_net
